blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ekropotin/quickmark/discussions
    about: For questions, ideas, and general discussion about QuickMark
  - name: 📖 Documentation
    url: https://github.com/ekropotin/quickmark/blob/main/README.md
    about: Check the README and documentation for usage information